function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(CSTParser.parse_array, (CSTParser.ParseState,))
    precompile(CSTParser.parse_call, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.parse_if, (CSTParser.ParseState, Bool, Array{Any, 1},))
    precompile(CSTParser.parse_call, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_call, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.parse_call, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000029)}},))
    precompile(CSTParser.parse_call, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.parse_call, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000023)}},))
    precompile(CSTParser.Type, (Type{Expr}, CSTParser.EXPR,))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.precedence, (Tokenize.Tokens.Token,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fc), false},))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000106), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false},))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000040)}, Array{Any, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f8), false},))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000101), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000105), false},))
    precompile(CSTParser.non_dotted_op, (Tokenize.Tokens.Token,))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser._lint_arg, (CSTParser.ParseState, CSTParser.EXPR, Array{Symbol, 1}, Int64, CSTParser.EXPR, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.IDENTIFIER, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, Bool,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.SyntaxNode, 1},))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000022)}},))
    precompile(CSTParser.parse_struct, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x00000053)},))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.parse_block, (CSTParser.ParseState, Int64, CSTParser.EXPR,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false},))
    precompile(CSTParser._lint_func_sig, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.closer, (CSTParser.ParseState, Void,))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser._lint_arg, (CSTParser.ParseState, CSTParser.IDENTIFIER, Array{Symbol, 1}, Int64, CSTParser.IDENTIFIER, Int64, Int64,))
    precompile(CSTParser.parse_unary, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000002e)}},))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000001e)}},))
    precompile(CSTParser._lint_arg, (CSTParser.ParseState, CSTParser.EXPR, Array{Symbol, 1}, Int64, CSTParser.IDENTIFIER, Int64, Int64,))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.get_id, (CSTParser.EXPR,))
    precompile(CSTParser.read_comment, (Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}},))
    precompile(CSTParser.parse_curly, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser._get_fname, (CSTParser.EXPR,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{2, Tokenize.Tokens.Kind(0x00000077), false},))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{Any, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_tuple, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{2, Tokenize.Tokens.Kind(0x00000077), false},))
    precompile(CSTParser.Type, (Type{CSTParser.Closer}, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.parse_ranges, (CSTParser.ParseState,))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.read_ws, (Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}}, Bool, Bool,))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000016)}},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000001b)}},))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fc), false},))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.parse_ref, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{15, Tokenize.Tokens.Kind(0x000002cf), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000105), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f9), false},))
    precompile(CSTParser.parse_list, (CSTParser.ParseState, Array{CSTParser.INSTANCE, 1},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000106), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000004e)}, Array{Any, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000101), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f8), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000108), false},))
    precompile(CSTParser.next, (CSTParser.ParseState,))
    precompile(CSTParser._arg_id, (CSTParser.EXPR,))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000ff), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000221), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false},))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{5, Tokenize.Tokens.Kind(0x000000f3), false},))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d4), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{4, Tokenize.Tokens.Kind(0x000000f0), false},))
    precompile(CSTParser.parse_doc, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004f)},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000227), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{CSTParser.IDENTIFIER, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.issyntaxcall, (CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.issyntaxcall, (CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{CSTParser.IDENTIFIER, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.LtoR, (Int64,))
    precompile(CSTParser.issyntaxcall, (CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000035)}, Array{CSTParser.INSTANCE, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000221), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000064), false},))
    precompile(CSTParser.parse_doc, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_call, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{11, Tokenize.Tokens.Kind(0x00000267), false},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.parse_string, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, CSTParser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000001e)}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x0000006f), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Any, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000010)}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.IDENTIFIER, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_compound, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000041)}, Array{CSTParser.IDENTIFIER, 1}, Int64, Array{CSTParser.INSTANCE, 1},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000000f)}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000016)}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000000f)}},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x0000006f), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{5, Tokenize.Tokens.Kind(0x000000f3), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000038)}, Array{CSTParser.EXPR, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{15, Tokenize.Tokens.Kind(0x000002cf), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000048)}, Array{CSTParser.EXPR, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser._track_assignment, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_macrocall, (CSTParser.ParseState,))
    precompile(CSTParser.ispunctuation, (Tokenize.Tokens.Token,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000002b)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{Any, 1},))
    precompile(CSTParser._track_assignment, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.EXPR,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000064), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000035)}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.unindent_triple_string, (CSTParser.ParseState,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{4, Tokenize.Tokens.Kind(0x000000f0), false}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003f)}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.EXPR,))
    precompile(CSTParser.parse_do, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000002e)}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser._track_assignment, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.IDENTIFIER,))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000000b)}},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.SyntaxNode, 1}, Int64,))
    precompile(CSTParser.isunaryop, (Tokenize.Tokens.Kind,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000047)}, Array{CSTParser.EXPR, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.ismacro, (CSTParser.EXPR,))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000010)}},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000048)}, Array{CSTParser.IDENTIFIER, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false},))
    precompile(CSTParser.parse_unary, (CSTParser.ParseState, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false},))
    precompile(CSTParser.isinstance, (Tokenize.Tokens.Token,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000046)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.EXPR, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000041)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000044)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d4), false},))
    precompile(CSTParser.Type, (Type{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}}, Int64, Int64, String,))
    precompile(CSTParser.parse, (CSTParser.ParseState, Bool,))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000031)}},))
    precompile(CSTParser._track_assignment, (CSTParser.ParseState, CSTParser.IDENTIFIER, CSTParser.EXPR,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{4, Tokenize.Tokens.Kind(0x000000f0), false}}, Int64, Int64,))
    precompile(CSTParser.parse_generator, (CSTParser.ParseState, CSTParser.IDENTIFIER,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000002b)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000029)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000023)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000023)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{Tokenize.Tokens.Kind(0x00000023)},))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000022)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.INSTANCE}, CSTParser.ParseState,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000002e)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000029)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.PUNCTUATION{Tokenize.Tokens.Kind(0x0000005b)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{15, Tokenize.Tokens.Kind(0x000002cf), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{Expr}, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false},))
    precompile(CSTParser.Type, (Type{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x00000052)}}, Int64, Int64, String,))
    precompile(CSTParser.Type, (Type{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004f)}}, Int64, Int64, String,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000108), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000227), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x0000006f), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fc), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004e)}}, Int64, Int64, String,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000101), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000056)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000001e)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000221), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000022)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{5, Tokenize.Tokens.Kind(0x000000f3), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{11, Tokenize.Tokens.Kind(0x00000267), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000024)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{Tokenize.Tokens.Kind(0x00000024)},))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000024)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000016)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.PUNCTUATION{Tokenize.Tokens.Kind(0x0000005a)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x00000053)}}, Int64, Int64, String,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000001b)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000064), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000000f)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000058)}}, Int64, Int64,))
    precompile(CSTParser.iskw, (Tokenize.Tokens.Token,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000106), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false}, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000105), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f9), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false}, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false}, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000002d)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{2, Tokenize.Tokens.Kind(0x00000077), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000000b)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000006)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000059)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000ff), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000031)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000010)}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000002f)}}, Int64, Int64,))
    precompile(CSTParser.parse_unary, (CSTParser.ParseState, CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d4), false}}, Int64, Int64,))
    precompile(CSTParser.parse_unary, (CSTParser.ParseState, CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(CSTParser.isunaryop, (CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false}}, Int64, Int64,))
    precompile(CSTParser._arg_id, (CSTParser.IDENTIFIER,))
    precompile(CSTParser.parse_unary, (CSTParser.ParseState, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(CSTParser.Type, (Type{CSTParser.Variable}, CSTParser.IDENTIFIER, Symbol, Symbol,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false}}, Int64, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000057)}}, Int64, Int64,))
    precompile(CSTParser.isunaryop, (CSTParser.IDENTIFIER,))
    precompile(CSTParser.Type, (Type{CSTParser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f8), false}}, Int64, Int64,))
    precompile(CSTParser.isunaryop, (CSTParser.EXPR,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000003f)}, Array{CSTParser.IDENTIFIER, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000048)}, Array{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64, Array{CSTParser.INSTANCE, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_expression, (CSTParser.ParseState,))
    precompile(CSTParser.get_id, (CSTParser.IDENTIFIER,))
    precompile(CSTParser.Type, (Type{CSTParser.ParseState}, Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}}, Bool, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Bool, Bool, Bool, Base.Dict{Any, Any}, Array{Any, 1}, CSTParser.Closer, CSTParser.Scope{Tokenize.Tokens.Kind(0x00000042)},))
    precompile(CSTParser.Type, (Type{CSTParser.LITERAL}, CSTParser.ParseState,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000041)}, Array{CSTParser.INSTANCE, 1}, Int64, Array{CSTParser.INSTANCE, 1},))
    precompile(CSTParser.parse_paren, (CSTParser.ParseState,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x0000001e)}, Array{CSTParser.SyntaxNode, 1}, Int64, Array{CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000031)}, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, CSTParser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{CSTParser.IDENTIFIER, 1}, Int64,))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{CSTParser.EXPR, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{CSTParser.EXPR, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{CSTParser.IDENTIFIER, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000035)}, Array{CSTParser.INSTANCE, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{CSTParser.IDENTIFIER, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.KEYWORD{Tokenize.Tokens.Kind(0x00000010)}, Array{CSTParser.EXPR, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{CSTParser.EXPR, 1}, Int64,))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x00000042)}, Array{Any, 1}, Int64, Array{Any, 1}, CSTParser.Scope{nothing},))
    precompile(CSTParser.Type, (Type{CSTParser.EXPR}, CSTParser.HEAD{Tokenize.Tokens.Kind(0x0000001e)}, Array{CSTParser.EXPR, 1}, Int64, Array{Any, 1},))
    precompile(CSTParser.lex_ws_comment, (Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}}, Char,))
    precompile(CSTParser.parse, (String, Bool,))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000002b)}},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(CSTParser.parse_operator, (CSTParser.ParseState, CSTParser.EXPR, CSTParser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false},))
    precompile(CSTParser.parse_kw, (CSTParser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000024)}},))
    precompile(CSTParser.Type, (Type{CSTParser.ParseState}, String,))
end
