function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Parser.parse_array, (Parser.ParseState,))
    precompile(Parser.parse_call, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.parse_if, (Parser.ParseState, Bool, Array{Any, 1},))
    precompile(Parser.parse_call, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_call, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.parse_call, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000029)}},))
    precompile(Parser.parse_call, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.parse_call, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000023)}},))
    precompile(Parser.format, (Parser.ParseState,))
    precompile(Parser.Type, (Type{Expr}, Parser.EXPR,))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.precedence, (Tokenize.Tokens.Token,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fc), false},))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000106), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false},))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000040)}, Array{Any, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f8), false},))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000101), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000105), false},))
    precompile(Parser.non_dotted_op, (Tokenize.Tokens.Token,))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser._lint_arg, (Parser.ParseState, Parser.EXPR, Array{Symbol, 1}, Int64, Parser.EXPR, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.IDENTIFIER, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_string, (Parser.ParseState, Bool,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.SyntaxNode, 1},))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000022)}},))
    precompile(Parser.parse_struct, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x00000053)},))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.parse_block, (Parser.ParseState, Int64, Parser.EXPR,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false},))
    precompile(Parser._lint_func_sig, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.closer, (Parser.ParseState, Void,))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser._lint_arg, (Parser.ParseState, Parser.IDENTIFIER, Array{Symbol, 1}, Int64, Parser.IDENTIFIER, Int64, Int64,))
    precompile(Parser.parse_unary, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000002e)}},))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000001e)}},))
    precompile(Parser._lint_arg, (Parser.ParseState, Parser.EXPR, Array{Symbol, 1}, Int64, Parser.IDENTIFIER, Int64, Int64,))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.get_id, (Parser.EXPR,))
    precompile(Parser.read_comment, (Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}},))
    precompile(Parser.parse_curly, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser._get_fname, (Parser.EXPR,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{2, Tokenize.Tokens.Kind(0x00000077), false},))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{Any, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_tuple, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{2, Tokenize.Tokens.Kind(0x00000077), false},))
    precompile(Parser.Type, (Type{Parser.Closer}, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Bool, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.parse_ranges, (Parser.ParseState,))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.read_ws, (Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}}, Bool, Bool,))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000016)}},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000001b)}},))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fc), false},))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.parse_ref, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{15, Tokenize.Tokens.Kind(0x000002cf), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000105), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f9), false},))
    precompile(Parser.parse_list, (Parser.ParseState, Array{Parser.INSTANCE, 1},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000106), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000004e)}, Array{Any, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000101), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f8), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000108), false},))
    precompile(Parser.next, (Parser.ParseState,))
    precompile(Parser._arg_id, (Parser.EXPR,))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000ff), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000221), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false},))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{5, Tokenize.Tokens.Kind(0x000000f3), false},))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d4), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{4, Tokenize.Tokens.Kind(0x000000f0), false},))
    precompile(Parser.parse_doc, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004f)},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000227), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{Parser.IDENTIFIER, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.issyntaxcall, (Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.issyntaxcall, (Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{Parser.IDENTIFIER, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.LtoR, (Int64,))
    precompile(Parser.issyntaxcall, (Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000035)}, Array{Parser.INSTANCE, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000221), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000064), false},))
    precompile(Parser.parse_doc, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_call, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false},))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{11, Tokenize.Tokens.Kind(0x00000267), false},))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.parse_string, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, Parser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000001e)}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x0000006f), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Any, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000010)}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.IDENTIFIER, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_juxtaposition, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000041)}, Array{Parser.IDENTIFIER, 1}, Int64, Array{Parser.INSTANCE, 1},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000000f)}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000016)}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000000f)}},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x0000006f), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{5, Tokenize.Tokens.Kind(0x000000f3), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000038)}, Array{Parser.EXPR, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{15, Tokenize.Tokens.Kind(0x000002cf), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000048)}, Array{Parser.EXPR, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{nothing},))
    precompile(Parser._track_assignment, (Parser.ParseState, Parser.EXPR, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_macrocall, (Parser.ParseState,))
    precompile(Parser.ispunctuation, (Tokenize.Tokens.Token,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000002b)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Any, 1},))
    precompile(Parser._track_assignment, (Parser.ParseState, Parser.EXPR, Parser.EXPR,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000064), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000035)}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.unindent_triple_string, (Parser.ParseState,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{4, Tokenize.Tokens.Kind(0x000000f0), false}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003f)}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.EXPR,))
    precompile(Parser.parse_do, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000002e)}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser._track_assignment, (Parser.ParseState, Parser.EXPR, Parser.IDENTIFIER,))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000000b)}},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.SyntaxNode, 1}, Int64,))
    precompile(Parser.isunaryop, (Tokenize.Tokens.Kind,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000047)}, Array{Parser.EXPR, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.ismacro, (Parser.EXPR,))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000010)}},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000048)}, Array{Parser.IDENTIFIER, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false},))
    precompile(Parser.parse_unary, (Parser.ParseState, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false},))
    precompile(Parser.isinstance, (Tokenize.Tokens.Token,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000046)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.EXPR, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000041)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000044)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.IDENTIFIER, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d4), false},))
    precompile(Parser.Type, (Type{Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}}, Int64, Int64, String,))
    precompile(Parser.parse, (Parser.ParseState, Bool,))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000031)}},))
    precompile(Parser._track_assignment, (Parser.ParseState, Parser.IDENTIFIER, Parser.EXPR,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{4, Tokenize.Tokens.Kind(0x000000f0), false}}, Int64, Int64,))
    precompile(Parser.parse_generator, (Parser.ParseState, Parser.IDENTIFIER,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000002b)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000029)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000023)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000023)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{Tokenize.Tokens.Kind(0x00000023)},))
    precompile(Parser.Type, (Type{Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000062), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000022)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.INSTANCE}, Parser.ParseState,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000002e)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f6), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000029)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.PUNCTUATION{Tokenize.Tokens.Kind(0x0000005b)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{15, Tokenize.Tokens.Kind(0x000002cf), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Expr}, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false},))
    precompile(Parser.Type, (Type{Parser.LITERAL{Tokenize.Tokens.Kind(0x00000052)}}, Int64, Int64, String,))
    precompile(Parser.Type, (Type{Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004f)}}, Int64, Int64, String,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000108), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000227), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x0000006f), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fc), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004e)}}, Int64, Int64, String,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000101), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000056)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000001e)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000221), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000fe), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000022)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{5, Tokenize.Tokens.Kind(0x000000f3), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{11, Tokenize.Tokens.Kind(0x00000267), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000024)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{Tokenize.Tokens.Kind(0x00000024)},))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000024)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000016)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.PUNCTUATION{Tokenize.Tokens.Kind(0x0000005a)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.LITERAL{Tokenize.Tokens.Kind(0x00000053)}}, Int64, Int64, String,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000001b)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000064), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{1, Tokenize.Tokens.Kind(0x00000061), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000000f)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000058)}}, Int64, Int64,))
    precompile(Parser.iskw, (Tokenize.Tokens.Token,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000106), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false}, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000105), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f9), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false}, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false}, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000002d)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{2, Tokenize.Tokens.Kind(0x00000077), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000000b)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003b)}, Array{Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000006)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000059)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000ff), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000031)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000010)}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000002f)}}, Int64, Int64,))
    precompile(Parser.parse_unary, (Parser.ParseState, Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x00000107), false},))
    precompile(Parser.Type, (Type{Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d4), false}}, Int64, Int64,))
    precompile(Parser.parse_unary, (Parser.ParseState, Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false},))
    precompile(Parser.isunaryop, (Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)},))
    precompile(Parser.Type, (Type{Parser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{20, Tokenize.Tokens.Kind(0x000002d1), false}}, Int64, Int64,))
    precompile(Parser._arg_id, (Parser.IDENTIFIER,))
    precompile(Parser.parse_unary, (Parser.ParseState, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false},))
    precompile(Parser.Type, (Type{Parser.Variable}, Parser.IDENTIFIER, Symbol, Symbol,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false}}, Int64, Int64,))
    precompile(Parser.Type, (Type{Parser.PUNCTUATION{Tokenize.Tokens.Kind(0x00000057)}}, Int64, Int64,))
    precompile(Parser.isunaryop, (Parser.IDENTIFIER,))
    precompile(Parser.Type, (Type{Parser.OPERATOR{6, Tokenize.Tokens.Kind(0x000000f8), false}}, Int64, Int64,))
    precompile(Parser.isunaryop, (Parser.EXPR,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000003f)}, Array{Parser.IDENTIFIER, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000048)}, Array{Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64, Array{Parser.INSTANCE, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_expression, (Parser.ParseState,))
    precompile(Parser.get_id, (Parser.IDENTIFIER,))
    precompile(Parser.Type, (Type{Parser.ParseState}, Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}}, Bool, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Tokenize.Tokens.Token, Bool, Bool, Bool, Base.Dict{Any, Any}, Array{Any, 1}, Parser.Closer, Parser.Scope{Tokenize.Tokens.Kind(0x00000042)},))
    precompile(Parser.Type, (Type{Parser.LITERAL}, Parser.ParseState,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000041)}, Array{Parser.INSTANCE, 1}, Int64, Array{Parser.INSTANCE, 1},))
    precompile(Parser.parse_paren, (Parser.ParseState,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x0000001e)}, Array{Parser.SyntaxNode, 1}, Int64, Array{Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000031)}, 1}, Parser.Scope{nothing},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, Parser.OPERATOR{8, Tokenize.Tokens.Kind(0x0000021b), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{Parser.IDENTIFIER, 1}, Int64,))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{0, Tokenize.Tokens.Kind(0x0000005f), false},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.LITERAL{Tokenize.Tokens.Kind(0x0000004c)}, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x0000021f), false}, Array{Parser.EXPR, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{Parser.EXPR, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.OPERATOR{14, Tokenize.Tokens.Kind(0x000002cc), false}, Array{Parser.IDENTIFIER, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000035)}, Array{Parser.INSTANCE, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000034)}, Array{Parser.IDENTIFIER, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.KEYWORD{Tokenize.Tokens.Kind(0x00000010)}, Array{Parser.EXPR, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000043)}, Array{Parser.EXPR, 1}, Int64,))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x00000042)}, Array{Any, 1}, Int64, Array{Any, 1}, Parser.Scope{nothing},))
    precompile(Parser.Type, (Type{Parser.EXPR}, Parser.HEAD{Tokenize.Tokens.Kind(0x0000001e)}, Array{Parser.EXPR, 1}, Int64, Array{Any, 1},))
    precompile(Parser.lex_ws_comment, (Tokenize.Lexers.Lexer{Base.AbstractIOBuffer{Array{UInt8, 1}}}, Char,))
    precompile(Parser.parse, (String, Bool,))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x0000002b)}},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{11, Tokenize.Tokens.Kind(0x0000025f), false},))
    precompile(Parser.parse_operator, (Parser.ParseState, Parser.EXPR, Parser.OPERATOR{9, Tokenize.Tokens.Kind(0x00000220), false},))
    precompile(Parser.parse_kw, (Parser.ParseState, Type{Base.Val{Tokenize.Tokens.Kind(0x00000024)}},))
    precompile(Parser.Type, (Type{Parser.ParseState}, String,))
end
